-- creating tables --

-- store user related information
CREATE TABLE account(
    user_id serial PRIMARY KEY,
    username VARCHAR (50) UNIQUE NOT NULL,
    password VARCHAR (50) NOT NULL,
    email VARCHAR (355) UNIQUE NOT NULL,
    created_on TIMESTAMP NOT NULL,
    last_login TIMESTAMP
);

-- different roles in application 
CREATE TABLE role(
    role_id serial PRIMARY KEY,
    role_name VARCHAR (255) UNIQUE NOT NULL
);

-- account_role - to manage the relationship between users and roles
CREATE TABLE account_role(
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    grant_date TIMESTAMP without time zone,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT account_role_role_id_fk FOREIGN KEY (role_id)
        REFERENCES role (role_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT account_role_user_id_fk FOREIGN KEY (user_id)
        REFERENCES account (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

/*
The primary key constraint ensures that each combination of 'user_id' and 'role_id' is unique.
PRIMARY KEY (user_id, role_id)

The foreign key constraint ensures that the values in a column match values in another table, creating a relationship between tables.
This helps maintain referential integrity across the database.
FOREIGN KEY (column) REFERENCES other_table (column) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE

The unique constraint ensures that all values in a column are distinct across the table.
UNIQUE (column)

NOT NULL constraint ensures that a column cannot contain a NULL value, enforcing data integrity.
column_name datatype NOT NULL
*/

-- 2. - SELECT INTO --
-- allows users to create a new table directly from the result set of a query.
-- SELECT INTO does not return data to the client but saves it in a new table.
-- syntax --
/*
SELECT column_list
INTO [TEMPORARY | TEMP | UNLOGGED] [TABLE] new_table_name
FROM table_name
WHERE condition;
*/

SELECT film_id, title, rental_rate
INTO TABLE film_r
FROM film
WHERE rating = 'R' AND rental_duration = 5
ORDER BY title;

SELECT
    film_id,
    title,
    length 
INTO TEMP TABLE short_film
FROM
    film
WHERE
    length < 60
ORDER BY
    title;

-- Create Auto-increment Column using SERIAL
-- SERIAL data type is a convenient way to create auto-increment columns, commonly used for primary keys.
-- using SERIAL, BIGSERIAL, or SMALLSERIAL, PostgreSQL assigns sequential values to our table, ensuring data integrity and easy referencing.

CREATE TABLE animals (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

INSERT INTO animals(name) 
VALUES('Dog');
INSERT INTO animals(name) 
VALUES('Cat');
SELECT * FROM animals;

-- confirming the unique identifier assigned to the newly inserted row.
INSERT INTO animals (name)
VALUES ('Tiger')
RETURNING id;


-- CREATE SEQUENCE --
-- allows developers to create a sequence that automatically generates unique numeric values.

CREATE SEQUENCE mysequence
INCREMENT 5
START 10;

SELECT nextval('mysequence');

-- Descending Sequence with Cycle
CREATE SEQUENCE three
INCREMENT -1 
MINVALUE -5
MAXVALUE 3
START 3
CYCLE;

SELECT nextval('three');

-- Sequence Associated with a Table Column
CREATE TABLE order_details(
    order_id SERIAL,
    item_id INT NOT NULL,
    product_id INT,
    product_name TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (order_id, item_id)
);

CREATE SEQUENCE order_item_id
START 10
INCREMENT 10
MINVALUE 10
OWNED BY order_details.item_id;

INSERT INTO 
    order_details(order_id, item_id, product_name, price)
VALUES
    (100, nextval('order_item_id'), 'DVD Player', 100),
    (100, nextval('order_item_id'), 'Android TV', 550),
    (100, nextval('order_item_id'), 'Speaker', 250);


SELECT order_id, item_id, product_name, price
FROM order_details;

-- Identity Column -- 
-- identity column is a specialized column type that automatically generates unique values for each row, making it ideal for primary keys and other unique identifiers. 
-- Syntax
-- column_name type GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY[ ( sequence_option ) ]

-- generated always
create table color (
    color_id int generated always as identity,
    color_name varchar not null
);

insert into color (color_name)
values ('Red');
select  *  from color;

insert into color (color_id, color_name)
values (2, 'Green');

insert into color(color_id, color_name)
OVERRIDING SYSTEM VALUE
VALUES (2, 'Green');

--  generated by default
drop table color;

CREATE TABLE color(
    color_id int generated by default as identity,
    color_name VARCHAR NOT NULL
);

INSERT INTO color (color_name)
VALUES
    ('White');
INSERT INTO color (color_id, color_name)
VALUES
    (2, 'Yellow');
SELECT * FROM color;

-- Using identity columns simplifies key generation and ensures consistency across applications, making them a powerful alternative to SERIAL in modern PostgreSQL databases.


-- ALTER TABLE --
-- allows us to modify the structure of an existing table to meet evolving database needs
-- With ALTER TABLE, we can add new columns, drop columns, rename columns, modify constraints, and much more. 

DROP TABLE links;
CREATE TABLE links (
    link_id serial,
    title VARCHAR (512) NOT NULL,
    url VARCHAR (1024) NOT  NULL UNIQUE
);


-- 1. add new column
ALTER TABLE links
ADD COLUMN active BOOLEAN;

-- 2. drop column
ALTER TABLE links
DROP COLUMN active;

-- 3. rename a column
ALTER TABLE links
RENAME COLUMN title to  link_title;

-- 4. Changing default value of a column
ALTER TABLE links
ALTER COLUMN target
SET DEFAULT '_blank';

ALTER TABLE links
ALTER COLUMN target
DROP DEFAULT;

-- changing NOT NULL Constraint
ALTER TABLE links
ALTER COLUMN target SET NOT NULL;

ALTER TABLE links
ALTER COLUMN target DROP NOT NULL;

-- adding a CHECK Constraint
-- CHECK constraints allow you to define a condition that the data in a column must meet.
ALTER TABLE links
ADD CONSTRAINT url_check CHECK (url LIKE 'http%');

-- adding a general constraint like UNIQUE, PRIMARY KEY, FOREIGN KEY
ALTER TABLE links
ADD CONSTRAINT link_id_pk PRIMARY KEY (link_id);

-- Renaming a Table --
ALTER TABLE links
RENAME TO website_links;

ALTER TABLE website_links
RENAME TO links;

ALTER table links
ADD COLUMN target VARCHAR (10);

INSERT INTO links (link_title, url) 
VALUES ('Postgres Tutorial', 'https://www.geeksforgeeks.org/');

SELECT * FROM links;

-- changing column types (from varchar to text)
ALTER TABLE products
ALTER COLUMN description TYPE TEXT;

SELECT * FROM order_details;

ALTER TABLE order_details
ALTER COLUMN product_id TYPE BIGINT;

-- rename columns
CREATE TABLE customers (
    id serial PRIMARY KEY,
    name VARCHAR NOT NULL,
    phone VARCHAR NOT NULL,
    email VARCHAR,
    group_id INT
);

INSERT INTO customers (name, phone, email, group_id)
VALUES 
('John Doe', '123567345', 'john@cile', 101),
('Jane Smith', '082355782', 'jane@mail', 102);

SELECT * FROM customers;

ALTER TABLE customers
RENAME COLUMN email TO contact_email;

ALTER TABLE customers 
RENAME COLUMN name TO customer_name;

ALTER TABLE customers
RENAME COLUMN phone TO contact_phone;

-- table with foreign key -- 
CREATE TABLE orders (
    order_id serial PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    FOREIGN KEY (customer_id) REFERENCES customers (id)
);

INSERT INTO orders (customer_id, order_date)
VALUES 
(1, '2024-01-15'),
(2, '2024-02-20');

ALTER TABLE orders  
DROP CONSTRAINT orders_customer_id_fkey;

ALTER TABLE orders  
RENAME COLUMN customer_id TO new_customer_id;

ALTER TABLE orders  
ADD CONSTRAINT orders_new_customer_id_fkey  
FOREIGN KEY (new_customer_id) REFERENCES customers (id);

SELECT * FROM orders;

-- truncate table --
-- provides a quick and efficient way to remove all data from large tables, freeing up storage space instantly.
-- used to delete all rows from a table without deleting the table structure itself
-- This command is ideal for fast data removal when the table structure, along with its indexes and constraints, needs to be preserved.
-- Compared to DELETE, TRUNCATE TABLE is much faster, as it avoids row-by-row processing.
-- Syntax: TRUNCATE TABLE table_name;

SELECT * FROM animals;

TRUNCATE TABLE animals;

SELECT * FROM galaxy;

TRUNCATE TABLE galaxy;

-- Temporary Table
-- is a powerful tool for managing session-specific data that only needs to exist for a short duration.
-- Temporary tables are created within a database session or transaction and are automatically dropped when the session ends, making them ideal for intermediate data storage.
-- Syntax

/*
CREATE TEMPORARY TABLE temp_table(
   ...
);
*/
CREATE TEMPORARY TABLE mytemp(
    order_id INT, 
    new_customer_id int,
    order_date TIMESTAMP
);

SELECT * FROM mytemp;

DROP TABLE mytemp;

-- copy a table
-- copying an existing table to a new table
-- This might come in handy while creating new tables that would either have the same data or data of the same table with certain operations performed on them.

-- Copy Table with the Same Structure and Data

CREATE TABLE students (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR,
    last_name VARCHAR,
    email VARCHAR UNIQUE
);

INSERT INTO students(first_name, last_name, email)
VALUES 
('Manuu', 'Temperu', 'manuutemperu@fgr.com'),
('Befewihf', 'Temferg', 'hffdae.@rtgg.com');

INSERT INTO students(first_name, last_name, email)
VALUES('Shreyas', 'Iyer', 'shreyas.iyer@gfg.com'),
    ('Rishabh', 'Pant', 'rishabh.pant@gfg.com');

SELECT * FROM students;

CREATE TABLE copy_students AS TABLE students;

SELECT * FROM copy_students;

-- copy table with the same structure and no Data
-- Syntax: CREATE TABLE new_table AS TABLE old_table WITH NO DATA;

CREATE TABLE without_data_students AS TABLE students WITH NO DATA;

SELECT * FROM without_data_students;

-- copy table with same structure and partial data
-- Syntax: CREATE TABLE new_table AS TABLE old_table WHERE condition;

CREATE TABLE copy_partial_students AS 
SELECT * FROM students
WHERE id IN (1,3);

SELECT * FROM copy_partial_students;

--- Comparing Tables --- 
-- commonly used techniques for comparing tables:
-- Using EXCEPT and UNION operators
-- Using OUTER JOIN

CREATE TABLE foo(
    id int PRIMARY KEY,
    name VARCHAR (50)
);

INSERT INTO foo (id, name)
VALUES
    (1,'a'), (2,'b');

CREATE TABLE bar(
    id int PRIMARY KEY,
    name VARCHAR (50)
);

INSERT INTO bar (id,name)
VALUES 
    (1, 'a'),
    (2, 'b');

UPDATE bar
SET name = 'c'
WHERE id = 2;

-- identify difference using EXCEPT
-- find the rows in the 'foo' table but not in the bar table
select id, name, 'not in bar' AS note 
FROM foo
EXCEPT 
    SELECT id, name, 'not in bar' AS note 
    FROM bar;

SELECT * FROM bar
EXCEPT SELECT * FROM foo;

-- Comparison using OUTER JOIN
-- It returns all rows when there is a match in either table, and fills with NULL where there is no match.
SELECT * from foo
FULL OUTER JOIN bar USING(id,name)
WHERE 
    foo.id IS NULL
    or bar.id IS NULL;

SELECT
    COUNT(*)
FROM
    foo
FULL OUTER JOIN bar USING (id,name)
WHERE 
    foo.id IS NULL
    OR bar.id IS NULL;

/*
EXCEPT-UNION: Best when you need clear, distinct differences between two datasets.
FULL OUTER JOIN: Useful for detailed comparisons, especially when working with complex datasets.
*/


-- DESCRIBE TABLE
-- to view table column details.
--  Using the pSQL shell: \d or \d+
--  Using information_schema
SELECT
    table_name,
    column_name,
    data_type
FROM
    information_schema.columns
WHERE 
    table_name = 'film';

SELECT *
FROM
    information_schema.columns
WHERE 
    table_name = 'film';

-- show tables

-- Using PSQL Shell: navigate to database by \c database_name 
-- then show tables by \dt

-- Using pg_catalog schema
SELECT * FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND
    schemaname != 'information_schema';

-- Using Information Schema
SELECT table_name
FROM information_schema.tables
WHERE table_schema NOT IN ('pg_catalog', 'information_schema');

-- Import csv file into table
-- a powerful and efficient way to bulk load data directly from a CSV file into a table.

-- Step 1: Creating a Target Table.

CREATE TABLE persons
(
  id serial NOT NULL,
  first_name character varying(50),
  last_name character varying(50),
  dob DATE,
  email character varying(255),
  CONSTRAINT persons_pkey PRIMARY KEY (id)
);

-- Step 3: Importing the CSV File
COPY persons(first_name, last_name, dob, email)
FROM 'C:/Program Files/PostgreSQL/17/data/persons.csv'
DELIMITER ',' CSV HEADER;

SELECT * FROM persons;

/*
It is important to put the CSV file path after the FROM keyword. Because CSV file format is used, you need to mention the DELIMITER as well as 'CSV' keywords. 

The HEADER keyword indicates that the CSV file comprises a header line with column names. 

The file must be read directly by the PostgreSQL server and not by the client application. 
you can execute the COPY statement successfully if you have superusers access.
*/



-- UPSERT Operation --
-- llows users to either insert a new row into a table or update an existing row if it already exists.

/*
# syntax:

INSERT INTO table_name (column1, column2, ...)
VALUES (value1, value2, ...)
ON CONFLICT (conflict_column)
DO NOTHING | DO UPDATE SET column1 = value1, column2 = value2, ...;

Use DO NOTHING to skip the insert if a conflict occurs, or
Use DO UPDATE to update the existing row with new values based on the conflict.

*/

CREATE TABLE inventory2(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL (10,2) NOT NULL,
    quantity INT NOT NULL
);

INSERT INTO inventory2 (name, price, quantity)
VALUES 
    ('Item A', 10.99, 100),
    ('Item B', 15.49, 200),
    ('Item C', 20.00, 150);

SELECT * FROM inventory2;

-- 

INSERT INTO inventory2 (id, name, price, quantity)
VALUES (1, 'Item A', 12.99, 120)
ON CONFLICT (id)
DO UPDATE SET
    price = EXCLUDED.price,
    quantity = EXCLUDED.quantity;

INSERT INTO inventory2 (id, name, price, quantity)
VALUES (4, 'Item D', 25.99, 80)
ON CONFLICT (id)
DO UPDATE SET
    price = EXCLUDED.price,
    quantity = EXCLUDED.quantity;


-- Using ON CONFLICT DO NOTHING
INSERT INTO inventory2 (id, name, price, quantity)
VALUES (1, 'Item A', 30.00, 100)
ON CONFLICT (id)
DO NOTHING;

SELECT * FROM inventory2;

