-- Stored Procedures
-- The store procedures define functions for creating triggers or custom aggregate functions.
-- Stored procedures provide a means to execute multiple SQL statements in a structured and reusable way.

-- They introduce advanced control structures and allow us to perform complex calculations, making it easier to build complex applications directly within the database.
-- PostgreSQL supports three main procedural languages: SQL, PL/pgSQL, and C. We can also add other languages, such as Perl, Python, and TCL, through extensions.

-- PostgreSQL divides procedural languages into two main categories:
-- Safe Languages: These can be used by any user and include languages like SQL and PL/pgSQL.
-- Sandboxed Languages: These are restricted to superusers because they can bypass security measures and access external resources. An example of a sandboxed language is C.

-- using PostgreSQL stored procedures:
-- Reduced network traffic: Stored procedures execute on the database server, so the application sends a single function call instead of multiple SQL statements, reducing the number of database round trips.
-- Increased performance: Increase application performance because the user-defined functions and stored procedures are pre-compiled and stored in the PostgreSQL database server.
-- Reusability: You can reuse stored procedures across multiple applications, making database management more efficient.
-- Centralized logic: With stored procedures, logic is centralized on the database server, which reduces the redundancy of code in different applications.

-- cons
-- Specialized skills required: Slowness in software development because stored procedure programming requires specialized skills that many developers do not possess.
-- Version management: Difficult to manage versions and hard to debug.
-- Portability issues: May not be portable to other database management systems e.g., MySQL or Microsoft SQL Server.



-- create a stored procedure that transfers funds from one account to another in a banking system.
drop table if exists accounts;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance NUMERIC(15, 2) NOT NULL,
    currency CHAR(3) NOT NULL,  -- 'USD', 'EUR', 'KES', etc.
    PRIMARY KEY(id)
);

-- Function to Format Balance with Currency Symbol.
CREATE OR REPLACE FUNCTION format_currency(amount NUMERIC, currency_code CHAR(3))
RETURNS TEXT 
AS $$
BEGIN
    RETURN
        case currency_code
            WHEN 'USD' THEN '$' || to_char(amount, 'FM999,999,999.00')
            WHEN 'EUR' THEN '€' || to_char(amount, 'FM999,999,999.00')
            WHEN 'KES' THEN 'KSh' || TO_CHAR(amount, 'FM999,999,999.00')
            WHEN 'GBP' THEN '£' || TO_CHAR(amount, 'FM999,999,999.00')
            ELSE currency_code || ' ' || TO_CHAR(amount, 'FM999,999,999.00')
        END;
END;
$$ LANGUAGE  plpgsql;

insert into accounts(name, balance, currency)
values('Raju', 170000,'KES'),
      ('Nikhil', 410000,'KES'),
      ('Manu', 230000,'KES'),
      ('Patel', 5672500,'KES'),
      ('Kenny', 542000,'KES');
SELECT * FROM accounts;
SELECT name, format_currency(balance, currency) as formatted_balance
FROM accounts;

-- stored procedure to transfer funds.
CREATE OR REPLACE PROCEDURE transfer(
    sender int,
    receiver int,
    amount decimal
)
AS $$
BEGIN
    -- Check if sender exists
    IF NOT EXISTS (SELECT 1 FROM accounts WHERE id = sender) THEN
        RAISE EXCEPTION 'Sender account (ID: %) does not exist', sender;
    END IF;

    -- Check if receiver exists
     IF NOT EXISTS (SELECT 1 FROM accounts WHERE id = receiver) THEN
        RAISE EXCEPTION 'Receiver account (ID: %) does not exist', receiver;
    END IF;

    -- Check if sender has enough balance
    IF (SELECT balance FROM accounts WHERE id = sender) < amount THEN
        RAISE EXCEPTION 'Insufficient Funds In sender''s account';
    END IF;

    -- subtracting amount from the sender
    UPDATE accounts
    SET balance = balance - amount
    WHERE id = sender;

    -- adding the amount to the receiver
    UPDATE accounts
    SET balance = balance + amount
    WHERE id = receiver;

    -- No COMMIT here; it is controlled by the client or outer transaction block

EXCEPTION WHEN OTHERS THEN
    -- any error will rollback the entire transaction
    RAISE NOTICE 'Transfer failed: %', SQLERRM;
    RAISE;
END;
$$ LANGUAGE plpgsql;

-- call inside a transaction:
BEGIN;
CALL transfer(4,2,15000.00);
COMMIT;

SELECT * FROM accounts;

-----
insert into accounts(name, balance, currency)
values('Dave', 17000,'KES');
SELECT * FROM accounts;
------
BEGIN;
CALL transfer(6,5,20000.00);
COMMIT;
------
BEGIN;
CALL transfer(5,45,30000.00);
COMMIT;
------
BEGIN;
CALL transfer(15,4,30000.00);
COMMIT;
------ automatic ---
CALL transfer(2,1,50000.00);
SELECT * FROM accounts;

-------
CALL transfer(2,11,50000.00);
SELECT * FROM accounts;


-- CREATE PROCEDURE: Syntax
/*
CREATE [OR REPLACE] PROCEDURE procedure_name(parameter_list)
LANGUAGE plpgsql
AS $$
DECLARE
    -- Variable declarations (optional)
BEGIN
    -- Procedure body (SQL statements)
END;
$$;
*/

-- parameter_list: The parameters for the stored procedure, which can have IN and INOUT modes. OUT mode is not supported.
-- LANGUAGE plpgsql: Specifies the procedural language. Other languages like SQL and C can also be used.
-- $$: Dollar-quoted string constant syntax to define the body of the stored procedure.

-- a procedure that inserts a record into an teams table.
CREATE TABLE team(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    points INT NOT NULL
);

CREATE OR REPLACE PROCEDURE add_team(team_name VARCHAR(255), team_points INT)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO team (name, points) VALUES (team_name, team_points);
END;
$$;

CALL add_team('FC Barcelona', 101);
CALL add_team('Real Madrid', 92);
-- ...
SELECT * FROM team;

-- procedure to update the table
CREATE OR REPLACE PROCEDURE update_team(team_name VARCHAR(255), new_points INT)
LANGUAGE plpgsql
AS $$
BEGIN
    -- check if the team exist
    IF NOT EXISTS (SELECT 1 FROM team where name = team_name) THEN
        RAISE EXCEPTION 'The team %, does not exist', team_name;
    END IF;

    UPDATE team SET points = new_points WHERE name = team_name;
END;
$$;

CALL update_team('Simba', 45);
CALL update_team('FC Barcelona', 96);

SELECT * FROM team ORDER BY points DESC;

--- procedure to add new column
CREATE OR REPLACE PROCEDURE add_column(
    column_name TEXT, column_type TEXT
)

LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format('ALTER TABLE team ADD COLUMN IF NOT EXISTS %I %s', column_name, column_type);
    RAISE NOTICE 'column % of type % has been added', column_name, column_type;
END;
$$;

--- create league table
CREATE TABLE league(
    league_id SERIAL PRIMARY KEY,
    league_name VARCHAR(100) NOT NULL UNIQUE,
    country VARCHAR(100)
);
/*
INSERT INTO league (league_name, country) VALUES 
('La Liga', 'Spain'),
('Premier League', 'England'),
('Bundesliga', 'Germany'),
('Serie A', 'Italy'),
('Ligue 1', 'France'),
... ;*/

SELECT * FROM league;
--- Add league_id to team table
ALTER TABLE team 
ADD COLUMN league_id int,
ADD constraint fk_league FOREIGN KEY (league_id) REFERENCES league(league_id);

--- update
--- la liga (id = 1)
UPDATE team
SET league_id = 1
WHERE name IN (
     'FC Barcelona', 'Real Madrid', 'Atletico Madrid', 'Sevilla FC', 'Villarreal CF'
);
-- Eredivisie (ID = 7)
UPDATE team SET league_id = 7 WHERE name = 'Ajax';

SELECT name, league_id FROM team ORDER BY league_id ,name ASC;


--- select into Temp Table to Rank EPL Teams ---
DROP TABLE IF EXISTS epl_ranking;

SELECT 
    id,
    name,
    points, 
    RANK() OVER (ORDER BY points DESC) as position
INTO TEMP epl_ranking
FROM team
WHERE league_id = 2;

SELECT * FROM epl_ranking;

--- join table --
SELECT 
    RANK() OVER (ORDER BY t.points DESC) AS Position,
    t.name as Club,
    t.points as Points,
    l.league_name AS League
FROM team AS t
JOIN league AS l ON t.league_id = l.league_id;


--- ranking teams in top 5 leagues
SELECT 
    RANK() OVER (ORDER BY t.points desc) as Position,
    t.name as Team,
    t.points as points,
    l.league_name as League
FROM team AS t 
JOIN league as l on t.league_id = l.league_id
WHERE l.league_id BETWEEN 1 AND 5; -- or <= 5


--- drop procedure
-- Syntax
-- DROP PROCEDURE [IF EXISTS] procedure_name (argument_list)
-- [CASCADE | RESTRICT];

-- CASCADE: Drops the procedure and its dependent objects.
-- RESTRICT: Default option; prevents dropping the procedure if it has dependent objects.

CREATE OR REPLACE PROCEDURE insert_actor(
    fname VARCHAR, 
    lname VARCHAR)
LANGUAGE plpgsql    
AS $$
BEGIN
    INSERT INTO actor(first_name, last_name)
    VALUES(fname, lname);
END;
$$;

DROP PROCEDURE insert_actor(VARCHAR, VARCHAR);

-- uses the 'split_part()' function to split the full name into first name and last name 
-- before inserting them into the actor table.
CREATE OR REPLACE PROCEDURE insert_actor(
    full_name VARCHAR
)
LANGUAGE plpgsql    
AS $$
DECLARE
    fname VARCHAR;
    lname VARCHAR; 
BEGIN
    SELECT 
        SPLIT_PART(full_name, ' ', 1),
        SPLIT_PART(full_name, ' ', 2)
    INTO fname,
         lname;

    INSERT INTO actor(first_name, last_name)
    VALUES(fname, lname);    
END;
$$;

DROP PROCEDURE insert_actor(VARCHAR);

--- procedure to  deletes an actor by id
CREATE OR REPLACE PROCEDURE delete_actor(
    p_actor_id INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM actor 
    WHERE actor_id = p_actor_id;
END; 
$$;

DROP PROCEDURE delete_actor;
--------------------------
-- show procedures
-- in psql: \df+ *.*

SELECT 
    n.nspname AS schema,
    p.proname AS procedure_name,
    pg_catalog.pg_get_function_arguments(p.oid) AS parameters,
    pg_catalog.pg_get_function_result(p.oid) AS return_type
FROM pg_catalog.pg_proc p
JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
WHERE p.prokind = 'p';  -- 'p' stands for procedure

SELECT proname
FROM pg_catalog.pg_proc
WHERE prokind = 'p' AND pronamespace = (
    SELECT oid FROM pg_namespace WHERE nspname = 'public'
);

